// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "feature_Loop_memcpy_boundingBoxes_boun.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic feature_Loop_memcpy_boundingBoxes_boun::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic feature_Loop_memcpy_boundingBoxes_boun::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> feature_Loop_memcpy_boundingBoxes_boun::ap_ST_st1_fsm_0 = "1";
const sc_lv<9> feature_Loop_memcpy_boundingBoxes_boun::ap_ST_st2_fsm_1 = "10";
const sc_lv<9> feature_Loop_memcpy_boundingBoxes_boun::ap_ST_st3_fsm_2 = "100";
const sc_lv<9> feature_Loop_memcpy_boundingBoxes_boun::ap_ST_st4_fsm_3 = "1000";
const sc_lv<9> feature_Loop_memcpy_boundingBoxes_boun::ap_ST_st5_fsm_4 = "10000";
const sc_lv<9> feature_Loop_memcpy_boundingBoxes_boun::ap_ST_st6_fsm_5 = "100000";
const sc_lv<9> feature_Loop_memcpy_boundingBoxes_boun::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<9> feature_Loop_memcpy_boundingBoxes_boun::ap_ST_pp0_stg0_fsm_7 = "10000000";
const sc_lv<9> feature_Loop_memcpy_boundingBoxes_boun::ap_ST_st11_fsm_8 = "100000000";
const sc_lv<32> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv1_1 = "1";
const sc_lv<1> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv1_0 = "0";
const sc_lv<3> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv3_0 = "000";
const sc_lv<2> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv2_0 = "00";
const sc_lv<4> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv4_0 = "0000";
const sc_lv<16> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv32_7 = "111";
const sc_lv<32> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv32_6 = "110";
const sc_lv<32> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv32_4 = "100";
const sc_lv<32> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv32_1 = "1";
const sc_lv<32> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv32_1F = "11111";
const sc_lv<3> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv3_4 = "100";
const sc_lv<3> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv3_1 = "1";
const sc_lv<2> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv2_2 = "10";
const sc_lv<2> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv2_1 = "1";
const sc_lv<32> feature_Loop_memcpy_boundingBoxes_boun::ap_const_lv32_8 = "1000";

feature_Loop_memcpy_boundingBoxes_boun::feature_Loop_memcpy_boundingBoxes_boun(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_8 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_8 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( boundingBoxes_3_out_i_i_reg_124 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_8 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( boundingBoxes_2_out_i_i_reg_136 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_8 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( boundingBoxes_3_2_reg_148 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_8 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( boundingBoxes_3_5_reg_160 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_8 );

    SC_METHOD(thread_ap_sig_bdd_122);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_135);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_142);
    sensitive << ( m_axi_bounding_RVALID );
    sensitive << ( exitcond_i_i_i_reg_323 );

    SC_METHOD(thread_ap_sig_bdd_181);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_186);
    sensitive << ( frame_in_out_full_n );
    sensitive << ( featureh_out_full_n );

    SC_METHOD(thread_ap_sig_bdd_28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_280);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_371);
    sensitive << ( m_axi_bounding_ARREADY );
    sensitive << ( ap_sig_bdd_122 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_7);
    sensitive << ( ap_sig_bdd_135 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_8);
    sensitive << ( ap_sig_bdd_280 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_28 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_181 );

    SC_METHOD(thread_ap_sig_ioackin_m_axi_bounding_ARREADY);
    sensitive << ( m_axi_bounding_ARREADY );
    sensitive << ( ap_reg_ioackin_m_axi_bounding_ARREADY );

    SC_METHOD(thread_boundingBoxes_3_1_fu_263_p3);
    sensitive << ( boundingBoxes_2_out_i_i_reg_136 );
    sensitive << ( or_cond_i_i_fu_235_p2 );
    sensitive << ( newSel_i_i_fu_256_p3 );

    SC_METHOD(thread_boundingBoxes_3_3_fu_271_p3);
    sensitive << ( boundingBoxes_3_2_reg_148 );
    sensitive << ( boundingBoxes_0_reg_339 );
    sensitive << ( sel_tmp2_i_i_fu_225_p2 );

    SC_METHOD(thread_boundingBoxes_3_4_fu_278_p3);
    sensitive << ( boundingBoxes_3_2_reg_148 );
    sensitive << ( sel_tmp4_i_i_fu_230_p2 );
    sensitive << ( boundingBoxes_3_3_fu_271_p3 );

    SC_METHOD(thread_boundingBoxes_3_6_fu_286_p3);
    sensitive << ( boundingBoxes_3_5_reg_160 );
    sensitive << ( boundingBoxes_0_reg_339 );
    sensitive << ( sel_tmp4_i_i_fu_230_p2 );

    SC_METHOD(thread_boundingBoxes_3_fu_248_p3);
    sensitive << ( boundingBoxes_3_out_i_i_reg_124 );
    sensitive << ( or_cond_i_i_fu_235_p2 );
    sensitive << ( newSel4_i_i_fu_241_p3 );

    SC_METHOD(thread_exitcond_i_i_i_fu_204_p2);
    sensitive << ( indvar_i_i_i_reg_172 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_7 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_142 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_featureh_out_din);
    sensitive << ( featureh );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_bdd_186 );

    SC_METHOD(thread_featureh_out_write);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_bdd_186 );

    SC_METHOD(thread_frame_in_out_din);
    sensitive << ( frame_in );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_bdd_186 );

    SC_METHOD(thread_frame_in_out_write);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_bdd_186 );

    SC_METHOD(thread_indvar_next_i_i_i_fu_210_p2);
    sensitive << ( indvar_i_i_i_reg_172 );

    SC_METHOD(thread_m_axi_bounding_ARADDR);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_122 );
    sensitive << ( tmp_11_fu_193_p1 );
    sensitive << ( ap_reg_ioackin_m_axi_bounding_ARREADY );

    SC_METHOD(thread_m_axi_bounding_ARBURST);

    SC_METHOD(thread_m_axi_bounding_ARCACHE);

    SC_METHOD(thread_m_axi_bounding_ARID);

    SC_METHOD(thread_m_axi_bounding_ARLEN);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_122 );
    sensitive << ( ap_reg_ioackin_m_axi_bounding_ARREADY );

    SC_METHOD(thread_m_axi_bounding_ARLOCK);

    SC_METHOD(thread_m_axi_bounding_ARPROT);

    SC_METHOD(thread_m_axi_bounding_ARQOS);

    SC_METHOD(thread_m_axi_bounding_ARREGION);

    SC_METHOD(thread_m_axi_bounding_ARSIZE);

    SC_METHOD(thread_m_axi_bounding_ARUSER);

    SC_METHOD(thread_m_axi_bounding_ARVALID);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_122 );
    sensitive << ( ap_reg_ioackin_m_axi_bounding_ARREADY );

    SC_METHOD(thread_m_axi_bounding_AWADDR);

    SC_METHOD(thread_m_axi_bounding_AWBURST);

    SC_METHOD(thread_m_axi_bounding_AWCACHE);

    SC_METHOD(thread_m_axi_bounding_AWID);

    SC_METHOD(thread_m_axi_bounding_AWLEN);

    SC_METHOD(thread_m_axi_bounding_AWLOCK);

    SC_METHOD(thread_m_axi_bounding_AWPROT);

    SC_METHOD(thread_m_axi_bounding_AWQOS);

    SC_METHOD(thread_m_axi_bounding_AWREGION);

    SC_METHOD(thread_m_axi_bounding_AWSIZE);

    SC_METHOD(thread_m_axi_bounding_AWUSER);

    SC_METHOD(thread_m_axi_bounding_AWVALID);

    SC_METHOD(thread_m_axi_bounding_BREADY);

    SC_METHOD(thread_m_axi_bounding_RREADY);
    sensitive << ( exitcond_i_i_i_reg_323 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_7 );
    sensitive << ( ap_sig_bdd_142 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_m_axi_bounding_WDATA);

    SC_METHOD(thread_m_axi_bounding_WID);

    SC_METHOD(thread_m_axi_bounding_WLAST);

    SC_METHOD(thread_m_axi_bounding_WSTRB);

    SC_METHOD(thread_m_axi_bounding_WUSER);

    SC_METHOD(thread_m_axi_bounding_WVALID);

    SC_METHOD(thread_newSel4_i_i_fu_241_p3);
    sensitive << ( boundingBoxes_3_out_i_i_reg_124 );
    sensitive << ( boundingBoxes_0_reg_339 );
    sensitive << ( sel_tmp_i_i_fu_220_p2 );

    SC_METHOD(thread_newSel_i_i_fu_256_p3);
    sensitive << ( boundingBoxes_2_out_i_i_reg_136 );
    sensitive << ( boundingBoxes_0_reg_339 );
    sensitive << ( sel_tmp_i_i_fu_220_p2 );

    SC_METHOD(thread_or_cond_i_i_fu_235_p2);
    sensitive << ( sel_tmp4_i_i_fu_230_p2 );
    sensitive << ( sel_tmp2_i_i_fu_225_p2 );

    SC_METHOD(thread_sel_tmp2_i_i_fu_225_p2);
    sensitive << ( ap_sig_bdd_142 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond_i_i_i_reg_323_pp0_it1 );
    sensitive << ( ap_reg_ppstg_tmp_12_reg_332_pp0_it1 );

    SC_METHOD(thread_sel_tmp4_i_i_fu_230_p2);
    sensitive << ( ap_sig_bdd_142 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond_i_i_i_reg_323_pp0_it1 );
    sensitive << ( ap_reg_ppstg_tmp_12_reg_332_pp0_it1 );

    SC_METHOD(thread_sel_tmp_i_i_fu_220_p2);
    sensitive << ( ap_sig_bdd_142 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond_i_i_i_reg_323_pp0_it1 );
    sensitive << ( ap_reg_ppstg_tmp_12_reg_332_pp0_it1 );

    SC_METHOD(thread_tmp_11_fu_193_p1);
    sensitive << ( tmp_fu_183_p4 );

    SC_METHOD(thread_tmp_12_fu_216_p1);
    sensitive << ( indvar_i_i_i_reg_172 );

    SC_METHOD(thread_tmp_fu_183_p4);
    sensitive << ( bounding1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_122 );
    sensitive << ( ap_sig_ioackin_m_axi_bounding_ARREADY );
    sensitive << ( exitcond_i_i_i_fu_204_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_142 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_sig_bdd_186 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000000001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ioackin_m_axi_bounding_ARREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "feature_Loop_memcpy_boundingBoxes_boun_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, m_axi_bounding_AWVALID, "(port)m_axi_bounding_AWVALID");
    sc_trace(mVcdFile, m_axi_bounding_AWREADY, "(port)m_axi_bounding_AWREADY");
    sc_trace(mVcdFile, m_axi_bounding_AWADDR, "(port)m_axi_bounding_AWADDR");
    sc_trace(mVcdFile, m_axi_bounding_AWID, "(port)m_axi_bounding_AWID");
    sc_trace(mVcdFile, m_axi_bounding_AWLEN, "(port)m_axi_bounding_AWLEN");
    sc_trace(mVcdFile, m_axi_bounding_AWSIZE, "(port)m_axi_bounding_AWSIZE");
    sc_trace(mVcdFile, m_axi_bounding_AWBURST, "(port)m_axi_bounding_AWBURST");
    sc_trace(mVcdFile, m_axi_bounding_AWLOCK, "(port)m_axi_bounding_AWLOCK");
    sc_trace(mVcdFile, m_axi_bounding_AWCACHE, "(port)m_axi_bounding_AWCACHE");
    sc_trace(mVcdFile, m_axi_bounding_AWPROT, "(port)m_axi_bounding_AWPROT");
    sc_trace(mVcdFile, m_axi_bounding_AWQOS, "(port)m_axi_bounding_AWQOS");
    sc_trace(mVcdFile, m_axi_bounding_AWREGION, "(port)m_axi_bounding_AWREGION");
    sc_trace(mVcdFile, m_axi_bounding_AWUSER, "(port)m_axi_bounding_AWUSER");
    sc_trace(mVcdFile, m_axi_bounding_WVALID, "(port)m_axi_bounding_WVALID");
    sc_trace(mVcdFile, m_axi_bounding_WREADY, "(port)m_axi_bounding_WREADY");
    sc_trace(mVcdFile, m_axi_bounding_WDATA, "(port)m_axi_bounding_WDATA");
    sc_trace(mVcdFile, m_axi_bounding_WSTRB, "(port)m_axi_bounding_WSTRB");
    sc_trace(mVcdFile, m_axi_bounding_WLAST, "(port)m_axi_bounding_WLAST");
    sc_trace(mVcdFile, m_axi_bounding_WID, "(port)m_axi_bounding_WID");
    sc_trace(mVcdFile, m_axi_bounding_WUSER, "(port)m_axi_bounding_WUSER");
    sc_trace(mVcdFile, m_axi_bounding_ARVALID, "(port)m_axi_bounding_ARVALID");
    sc_trace(mVcdFile, m_axi_bounding_ARREADY, "(port)m_axi_bounding_ARREADY");
    sc_trace(mVcdFile, m_axi_bounding_ARADDR, "(port)m_axi_bounding_ARADDR");
    sc_trace(mVcdFile, m_axi_bounding_ARID, "(port)m_axi_bounding_ARID");
    sc_trace(mVcdFile, m_axi_bounding_ARLEN, "(port)m_axi_bounding_ARLEN");
    sc_trace(mVcdFile, m_axi_bounding_ARSIZE, "(port)m_axi_bounding_ARSIZE");
    sc_trace(mVcdFile, m_axi_bounding_ARBURST, "(port)m_axi_bounding_ARBURST");
    sc_trace(mVcdFile, m_axi_bounding_ARLOCK, "(port)m_axi_bounding_ARLOCK");
    sc_trace(mVcdFile, m_axi_bounding_ARCACHE, "(port)m_axi_bounding_ARCACHE");
    sc_trace(mVcdFile, m_axi_bounding_ARPROT, "(port)m_axi_bounding_ARPROT");
    sc_trace(mVcdFile, m_axi_bounding_ARQOS, "(port)m_axi_bounding_ARQOS");
    sc_trace(mVcdFile, m_axi_bounding_ARREGION, "(port)m_axi_bounding_ARREGION");
    sc_trace(mVcdFile, m_axi_bounding_ARUSER, "(port)m_axi_bounding_ARUSER");
    sc_trace(mVcdFile, m_axi_bounding_RVALID, "(port)m_axi_bounding_RVALID");
    sc_trace(mVcdFile, m_axi_bounding_RREADY, "(port)m_axi_bounding_RREADY");
    sc_trace(mVcdFile, m_axi_bounding_RDATA, "(port)m_axi_bounding_RDATA");
    sc_trace(mVcdFile, m_axi_bounding_RLAST, "(port)m_axi_bounding_RLAST");
    sc_trace(mVcdFile, m_axi_bounding_RID, "(port)m_axi_bounding_RID");
    sc_trace(mVcdFile, m_axi_bounding_RUSER, "(port)m_axi_bounding_RUSER");
    sc_trace(mVcdFile, m_axi_bounding_RRESP, "(port)m_axi_bounding_RRESP");
    sc_trace(mVcdFile, m_axi_bounding_BVALID, "(port)m_axi_bounding_BVALID");
    sc_trace(mVcdFile, m_axi_bounding_BREADY, "(port)m_axi_bounding_BREADY");
    sc_trace(mVcdFile, m_axi_bounding_BRESP, "(port)m_axi_bounding_BRESP");
    sc_trace(mVcdFile, m_axi_bounding_BID, "(port)m_axi_bounding_BID");
    sc_trace(mVcdFile, m_axi_bounding_BUSER, "(port)m_axi_bounding_BUSER");
    sc_trace(mVcdFile, bounding1, "(port)bounding1");
    sc_trace(mVcdFile, frame_in, "(port)frame_in");
    sc_trace(mVcdFile, featureh, "(port)featureh");
    sc_trace(mVcdFile, frame_in_out_din, "(port)frame_in_out_din");
    sc_trace(mVcdFile, frame_in_out_full_n, "(port)frame_in_out_full_n");
    sc_trace(mVcdFile, frame_in_out_write, "(port)frame_in_out_write");
    sc_trace(mVcdFile, featureh_out_din, "(port)featureh_out_din");
    sc_trace(mVcdFile, featureh_out_full_n, "(port)featureh_out_full_n");
    sc_trace(mVcdFile, featureh_out_write, "(port)featureh_out_write");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_28, "ap_sig_bdd_28");
    sc_trace(mVcdFile, boundingBoxes_3_out_i_i_reg_124, "boundingBoxes_3_out_i_i_reg_124");
    sc_trace(mVcdFile, boundingBoxes_2_out_i_i_reg_136, "boundingBoxes_2_out_i_i_reg_136");
    sc_trace(mVcdFile, boundingBoxes_3_2_reg_148, "boundingBoxes_3_2_reg_148");
    sc_trace(mVcdFile, boundingBoxes_3_5_reg_160, "boundingBoxes_3_5_reg_160");
    sc_trace(mVcdFile, indvar_i_i_i_reg_172, "indvar_i_i_i_reg_172");
    sc_trace(mVcdFile, ap_sig_bdd_122, "ap_sig_bdd_122");
    sc_trace(mVcdFile, ap_sig_ioackin_m_axi_bounding_ARREADY, "ap_sig_ioackin_m_axi_bounding_ARREADY");
    sc_trace(mVcdFile, exitcond_i_i_i_fu_204_p2, "exitcond_i_i_i_fu_204_p2");
    sc_trace(mVcdFile, exitcond_i_i_i_reg_323, "exitcond_i_i_i_reg_323");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_7, "ap_sig_cseq_ST_pp0_stg0_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_135, "ap_sig_bdd_135");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_sig_bdd_142, "ap_sig_bdd_142");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_i_i_i_reg_323_pp0_it1, "ap_reg_ppstg_exitcond_i_i_i_reg_323_pp0_it1");
    sc_trace(mVcdFile, indvar_next_i_i_i_fu_210_p2, "indvar_next_i_i_i_fu_210_p2");
    sc_trace(mVcdFile, tmp_12_fu_216_p1, "tmp_12_fu_216_p1");
    sc_trace(mVcdFile, tmp_12_reg_332, "tmp_12_reg_332");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_12_reg_332_pp0_it1, "ap_reg_ppstg_tmp_12_reg_332_pp0_it1");
    sc_trace(mVcdFile, boundingBoxes_0_reg_339, "boundingBoxes_0_reg_339");
    sc_trace(mVcdFile, boundingBoxes_3_fu_248_p3, "boundingBoxes_3_fu_248_p3");
    sc_trace(mVcdFile, boundingBoxes_3_1_fu_263_p3, "boundingBoxes_3_1_fu_263_p3");
    sc_trace(mVcdFile, boundingBoxes_3_4_fu_278_p3, "boundingBoxes_3_4_fu_278_p3");
    sc_trace(mVcdFile, boundingBoxes_3_6_fu_286_p3, "boundingBoxes_3_6_fu_286_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_181, "ap_sig_bdd_181");
    sc_trace(mVcdFile, ap_sig_bdd_186, "ap_sig_bdd_186");
    sc_trace(mVcdFile, tmp_11_fu_193_p1, "tmp_11_fu_193_p1");
    sc_trace(mVcdFile, ap_reg_ioackin_m_axi_bounding_ARREADY, "ap_reg_ioackin_m_axi_bounding_ARREADY");
    sc_trace(mVcdFile, tmp_fu_183_p4, "tmp_fu_183_p4");
    sc_trace(mVcdFile, sel_tmp4_i_i_fu_230_p2, "sel_tmp4_i_i_fu_230_p2");
    sc_trace(mVcdFile, sel_tmp2_i_i_fu_225_p2, "sel_tmp2_i_i_fu_225_p2");
    sc_trace(mVcdFile, sel_tmp_i_i_fu_220_p2, "sel_tmp_i_i_fu_220_p2");
    sc_trace(mVcdFile, or_cond_i_i_fu_235_p2, "or_cond_i_i_fu_235_p2");
    sc_trace(mVcdFile, newSel4_i_i_fu_241_p3, "newSel4_i_i_fu_241_p3");
    sc_trace(mVcdFile, newSel_i_i_fu_256_p3, "newSel_i_i_fu_256_p3");
    sc_trace(mVcdFile, boundingBoxes_3_3_fu_271_p3, "boundingBoxes_3_3_fu_271_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_8, "ap_sig_cseq_ST_st11_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_280, "ap_sig_bdd_280");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_bdd_371, "ap_sig_bdd_371");
#endif

    }
}

feature_Loop_memcpy_boundingBoxes_boun::~feature_Loop_memcpy_boundingBoxes_boun() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_8.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ioackin_m_axi_bounding_ARREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) {
            if (!(ap_sig_bdd_122.read() || esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_bounding_ARREADY.read()))) {
                ap_reg_ioackin_m_axi_bounding_ARREADY = ap_const_logic_0;
            } else if (ap_sig_bdd_371.read()) {
                ap_reg_ioackin_m_axi_bounding_ARREADY = ap_const_logic_1;
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_7.read()) && 
             !(ap_sig_bdd_142.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_i_fu_204_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                    !ap_sig_bdd_186.read())) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_7.read()) && 
             !(ap_sig_bdd_142.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_i_fu_204_p2.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                     !ap_sig_bdd_186.read()) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_7.read()) && 
                     !(ap_sig_bdd_142.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_i_fu_204_p2.read())))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (!(ap_sig_bdd_142.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                    !ap_sig_bdd_186.read())) {
            ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !(ap_sig_bdd_142.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_i_fu_204_p2.read()))) {
        indvar_i_i_i_reg_172 = indvar_next_i_i_i_fu_210_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                !ap_sig_bdd_186.read())) {
        indvar_i_i_i_reg_172 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_7.read()) && !(ap_sig_bdd_142.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        ap_reg_ppstg_exitcond_i_i_i_reg_323_pp0_it1 = exitcond_i_i_i_reg_323.read();
        ap_reg_ppstg_tmp_12_reg_332_pp0_it1 = tmp_12_reg_332.read();
        exitcond_i_i_i_reg_323 = exitcond_i_i_i_fu_204_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_i_reg_323.read()) && !(ap_sig_bdd_142.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        boundingBoxes_0_reg_339 = m_axi_bounding_RDATA.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && !(ap_sig_bdd_142.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_i_i_i_reg_323_pp0_it1.read()))) {
        boundingBoxes_2_out_i_i_reg_136 = boundingBoxes_3_1_fu_263_p3.read();
        boundingBoxes_3_2_reg_148 = boundingBoxes_3_4_fu_278_p3.read();
        boundingBoxes_3_5_reg_160 = boundingBoxes_3_6_fu_286_p3.read();
        boundingBoxes_3_out_i_i_reg_124 = boundingBoxes_3_fu_248_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_7.read()) && !(ap_sig_bdd_142.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_i_fu_204_p2.read()))) {
        tmp_12_reg_332 = tmp_12_fu_216_p1.read();
    }
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_8.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_8.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_return_0() {
    ap_return_0 = boundingBoxes_3_out_i_i_reg_124.read();
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_return_1() {
    ap_return_1 = boundingBoxes_2_out_i_i_reg_136.read();
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_return_2() {
    ap_return_2 = boundingBoxes_3_2_reg_148.read();
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_return_3() {
    ap_return_3 = boundingBoxes_3_5_reg_160.read();
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_sig_bdd_122() {
    ap_sig_bdd_122 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_sig_bdd_135() {
    ap_sig_bdd_135 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_sig_bdd_142() {
    ap_sig_bdd_142 = (esl_seteq<1,1,1>(m_axi_bounding_RVALID.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_i_reg_323.read()));
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_sig_bdd_181() {
    ap_sig_bdd_181 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_sig_bdd_186() {
    ap_sig_bdd_186 = (esl_seteq<1,1,1>(frame_in_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(featureh_out_full_n.read(), ap_const_logic_0));
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_sig_bdd_28() {
    ap_sig_bdd_28 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_sig_bdd_280() {
    ap_sig_bdd_280 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_sig_bdd_371() {
    ap_sig_bdd_371 = (esl_seteq<1,1,1>(ap_const_logic_1, m_axi_bounding_ARREADY.read()) && !ap_sig_bdd_122.read());
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_sig_cseq_ST_pp0_stg0_fsm_7() {
    if (ap_sig_bdd_135.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_7 = ap_const_logic_0;
    }
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_sig_cseq_ST_st11_fsm_8() {
    if (ap_sig_bdd_280.read()) {
        ap_sig_cseq_ST_st11_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_8 = ap_const_logic_0;
    }
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_28.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_181.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_sig_ioackin_m_axi_bounding_ARREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_bounding_ARREADY.read())) {
        ap_sig_ioackin_m_axi_bounding_ARREADY = m_axi_bounding_ARREADY.read();
    } else {
        ap_sig_ioackin_m_axi_bounding_ARREADY = ap_const_logic_1;
    }
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_boundingBoxes_3_1_fu_263_p3() {
    boundingBoxes_3_1_fu_263_p3 = (!or_cond_i_i_fu_235_p2.read()[0].is_01())? sc_lv<16>(): ((or_cond_i_i_fu_235_p2.read()[0].to_bool())? boundingBoxes_2_out_i_i_reg_136.read(): newSel_i_i_fu_256_p3.read());
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_boundingBoxes_3_3_fu_271_p3() {
    boundingBoxes_3_3_fu_271_p3 = (!sel_tmp2_i_i_fu_225_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp2_i_i_fu_225_p2.read()[0].to_bool())? boundingBoxes_0_reg_339.read(): boundingBoxes_3_2_reg_148.read());
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_boundingBoxes_3_4_fu_278_p3() {
    boundingBoxes_3_4_fu_278_p3 = (!sel_tmp4_i_i_fu_230_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp4_i_i_fu_230_p2.read()[0].to_bool())? boundingBoxes_3_2_reg_148.read(): boundingBoxes_3_3_fu_271_p3.read());
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_boundingBoxes_3_6_fu_286_p3() {
    boundingBoxes_3_6_fu_286_p3 = (!sel_tmp4_i_i_fu_230_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp4_i_i_fu_230_p2.read()[0].to_bool())? boundingBoxes_0_reg_339.read(): boundingBoxes_3_5_reg_160.read());
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_boundingBoxes_3_fu_248_p3() {
    boundingBoxes_3_fu_248_p3 = (!or_cond_i_i_fu_235_p2.read()[0].is_01())? sc_lv<16>(): ((or_cond_i_i_fu_235_p2.read()[0].to_bool())? boundingBoxes_3_out_i_i_reg_124.read(): newSel4_i_i_fu_241_p3.read());
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_exitcond_i_i_i_fu_204_p2() {
    exitcond_i_i_i_fu_204_p2 = (!indvar_i_i_i_reg_172.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(indvar_i_i_i_reg_172.read() == ap_const_lv3_4);
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_featureh_out_din() {
    featureh_out_din = featureh.read();
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_featureh_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
         !ap_sig_bdd_186.read())) {
        featureh_out_write = ap_const_logic_1;
    } else {
        featureh_out_write = ap_const_logic_0;
    }
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_frame_in_out_din() {
    frame_in_out_din = frame_in.read();
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_frame_in_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
         !ap_sig_bdd_186.read())) {
        frame_in_out_write = ap_const_logic_1;
    } else {
        frame_in_out_write = ap_const_logic_0;
    }
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_indvar_next_i_i_i_fu_210_p2() {
    indvar_next_i_i_i_fu_210_p2 = (!indvar_i_i_i_reg_172.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(indvar_i_i_i_reg_172.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_ARADDR() {
    m_axi_bounding_ARADDR =  (sc_lv<32>) (tmp_11_fu_193_p1.read());
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_ARBURST() {
    m_axi_bounding_ARBURST = ap_const_lv2_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_ARCACHE() {
    m_axi_bounding_ARCACHE = ap_const_lv4_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_ARID() {
    m_axi_bounding_ARID = ap_const_lv1_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_ARLEN() {
    m_axi_bounding_ARLEN = ap_const_lv32_4;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_ARLOCK() {
    m_axi_bounding_ARLOCK = ap_const_lv2_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_ARPROT() {
    m_axi_bounding_ARPROT = ap_const_lv3_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_ARQOS() {
    m_axi_bounding_ARQOS = ap_const_lv4_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_ARREGION() {
    m_axi_bounding_ARREGION = ap_const_lv4_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_ARSIZE() {
    m_axi_bounding_ARSIZE = ap_const_lv3_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_ARUSER() {
    m_axi_bounding_ARUSER = ap_const_lv1_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_ARVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_122.read() && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_bounding_ARREADY.read()))) {
        m_axi_bounding_ARVALID = ap_const_logic_1;
    } else {
        m_axi_bounding_ARVALID = ap_const_logic_0;
    }
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_AWADDR() {
    m_axi_bounding_AWADDR = ap_const_lv32_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_AWBURST() {
    m_axi_bounding_AWBURST = ap_const_lv2_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_AWCACHE() {
    m_axi_bounding_AWCACHE = ap_const_lv4_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_AWID() {
    m_axi_bounding_AWID = ap_const_lv1_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_AWLEN() {
    m_axi_bounding_AWLEN = ap_const_lv32_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_AWLOCK() {
    m_axi_bounding_AWLOCK = ap_const_lv2_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_AWPROT() {
    m_axi_bounding_AWPROT = ap_const_lv3_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_AWQOS() {
    m_axi_bounding_AWQOS = ap_const_lv4_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_AWREGION() {
    m_axi_bounding_AWREGION = ap_const_lv4_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_AWSIZE() {
    m_axi_bounding_AWSIZE = ap_const_lv3_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_AWUSER() {
    m_axi_bounding_AWUSER = ap_const_lv1_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_AWVALID() {
    m_axi_bounding_AWVALID = ap_const_logic_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_BREADY() {
    m_axi_bounding_BREADY = ap_const_logic_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_RREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_i_reg_323.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_142.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        m_axi_bounding_RREADY = ap_const_logic_1;
    } else {
        m_axi_bounding_RREADY = ap_const_logic_0;
    }
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_WDATA() {
    m_axi_bounding_WDATA = ap_const_lv16_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_WID() {
    m_axi_bounding_WID = ap_const_lv1_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_WLAST() {
    m_axi_bounding_WLAST = ap_const_logic_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_WSTRB() {
    m_axi_bounding_WSTRB = ap_const_lv2_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_WUSER() {
    m_axi_bounding_WUSER = ap_const_lv1_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_m_axi_bounding_WVALID() {
    m_axi_bounding_WVALID = ap_const_logic_0;
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_newSel4_i_i_fu_241_p3() {
    newSel4_i_i_fu_241_p3 = (!sel_tmp_i_i_fu_220_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp_i_i_fu_220_p2.read()[0].to_bool())? boundingBoxes_3_out_i_i_reg_124.read(): boundingBoxes_0_reg_339.read());
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_newSel_i_i_fu_256_p3() {
    newSel_i_i_fu_256_p3 = (!sel_tmp_i_i_fu_220_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp_i_i_fu_220_p2.read()[0].to_bool())? boundingBoxes_0_reg_339.read(): boundingBoxes_2_out_i_i_reg_136.read());
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_or_cond_i_i_fu_235_p2() {
    or_cond_i_i_fu_235_p2 = (sel_tmp4_i_i_fu_230_p2.read() | sel_tmp2_i_i_fu_225_p2.read());
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_sel_tmp2_i_i_fu_225_p2() {
    sel_tmp2_i_i_fu_225_p2 = (!ap_reg_ppstg_tmp_12_reg_332_pp0_it1.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(ap_reg_ppstg_tmp_12_reg_332_pp0_it1.read() == ap_const_lv2_1);
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_sel_tmp4_i_i_fu_230_p2() {
    sel_tmp4_i_i_fu_230_p2 = (!ap_reg_ppstg_tmp_12_reg_332_pp0_it1.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(ap_reg_ppstg_tmp_12_reg_332_pp0_it1.read() == ap_const_lv2_0);
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_sel_tmp_i_i_fu_220_p2() {
    sel_tmp_i_i_fu_220_p2 = (!ap_reg_ppstg_tmp_12_reg_332_pp0_it1.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(ap_reg_ppstg_tmp_12_reg_332_pp0_it1.read() == ap_const_lv2_2);
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_tmp_11_fu_193_p1() {
    tmp_11_fu_193_p1 = esl_zext<64,31>(tmp_fu_183_p4.read());
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_tmp_12_fu_216_p1() {
    tmp_12_fu_216_p1 = indvar_i_i_i_reg_172.read().range(2-1, 0);
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_tmp_fu_183_p4() {
    tmp_fu_183_p4 = bounding1.read().range(31, 1);
}

void feature_Loop_memcpy_boundingBoxes_boun::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!(ap_sig_bdd_122.read() || esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_bounding_ARREADY.read()))) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            if (!ap_sig_bdd_186.read()) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_7;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            }
            break;
        case 128 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && !(ap_sig_bdd_142.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !(ap_sig_bdd_142.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_i_fu_204_p2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_7;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !(ap_sig_bdd_142.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  !(ap_sig_bdd_142.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_i_fu_204_p2.read()) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_st11_fsm_8;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_7;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXX";
            break;
    }
}

}

